# Generated by Django 4.0.6 on 2022-09-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('opt1', models.CharField(max_length=255)),
                ('opt2', models.CharField(max_length=255)),
                ('opt3', models.CharField(max_length=255)),
                ('opt4', models.CharField(max_length=255)),
            ],
        ),
    ]
